name: android_bluetooth_printer
description: A plugin for Android Bluetooth Printer
version: 0.1.1
homepage: https://www.renseki.com

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.renseki.lib.android_bluetooth_printer
        pluginClass: AndroidBluetoothPrinterPlugin